### PR TITLE
Update r2.po

### PR DESCRIPTION
**Pull request by 495QhIp**

### CODE REVIEW

**Comment by intxcc** [comment]
Sadly "reddit's translation files - USE CROWDIN TO SUBMIT TRANSLATIONS. Direct pull requests to this repository will, generally, be rejected. https://crowdin.net/project/reddit".

But this is stupid. No one will try to get into the translation team for finding a small typo. Can someone authorized please make a mailing list or another way to report small fixes?

**Comment by kjoconnor** [comment]
It's not that hard to get started with crowdin, I swear! We use it as it makes it much easier for us to manage and deploy the translations.

Sorry if it's too much trouble, but thanks anyway!

**Comment by intxcc** [comment]
I agree with you, that it is not hard to get started with crowdin. I even made an account to add the fix from this commit. 

But one needs to get approved for the translation team, which will not only look like too much commitment for a small fix for most people, but you will also lose the overview of the team and who is able to commit translation code to the source.

You should at least have a subreddit where one can make an own thread or create a fixed thread for each language, where the translation team for each language can look into once in a while.

**Comment by kjoconnor** [comment]
Thanks for the thoughtful response. You raise some good points, but unfortunately we don't have a much better solution at the moment. The process as it is has gotten us this far, so that's why we've stuck with it.

To directly address the feedback:

> You should at least have a subreddit where one can make an own thread or create a fixed thread for each language, where the translation team for each language can look into once in a while.

I'm not sure I understand what the purpose of this would be - is it for properly crediting the translators? Or something else you were interested in?

Thanks again!

**Pull request closed without merging**
